Razor_Pre_TPI_AppartRental/Controllers/AppartementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Razor_Pre_TPI_AppartRental.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Razor_Pre_TPI_AppartRental.Models;

namespace Razor_Pre_TPI_AppartRental.Controllers
{

    [Authorize]
    public class AppartementsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public AppartementsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<string> GetCurrentUserId()
        {
            ApplicationUser usr = await GetCurrentUserAsync();
            return usr?.Id;
        }

        [HttpGet]
        public async Task<JsonResult> Test()
        {
            int retval = 0;

            await _userManager.AddToRoleAsync(await GetCurrentUserAsync(), "Admin");
            

            return Json(retval);
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: Appartements
        public async Task<IActionResult> Index()
        {
            var userId = await GetCurrentUserId();

            var model = await _context.Appartements.Select(x =>
                new AppartementViewModel
                {
                    AppartementId = x.Id,
                    Title = x.Title,
                    Surface = x.Surface,
                    Year = x.Year,
                    Rating = x.Rating
                }).ToListAsync();

            foreach (var item in model)
            {
                var m = await _context.UserAppartements.FirstOrDefaultAsync(x => x.UserId == userId && x.AppartementId == item.AppartementId);
                //var m = await _context.Appartements.FirstOrDefaultAsync(x => x.Id == item.AppartementId);
                if (m != null)
                {
                    item.InWishlist = true;
                    //item.Visited = m.Visited; // pas important car j'en ai pas besoin pour l'instant
                    //item.Rated = m.Rated; // pas important car j'en ai pas besoin pour l'instant
                    item.Rated = m.Rated;
                }
            }
            
            return View(model);
        }

        // GET: Appartements/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appartement = await _context.Appartements.FirstOrDefaultAsync(m => m.Id == id);
            if (appartement == null)
            {
                return NotFound();
            }

            return View(appartement);
        }

        // GET: Appartements/Create
        [Authorize(Roles = "Admin")] // OR : les roles séparés pas une virgule. AND : une ligne pour chaque role
        public IActionResult Create()
        {
            return View();
        }

        // POST: Appartements/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Year,Surface")] Appartement appartement) // TODO : voir si l'on doit ajouter Rating ici
        {
            if (ModelState.IsValid)
            {
                _context.Add(appartement);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(appartement);
        }

        // GET: Appartements/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appartement = await _context.Appartements.FindAsync(id);
            if (appartement == null)
            {
                return NotFound();
            }
            return View(appartement);
        }

        // POST: Appartements/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Year,Surface")] Appartement appartement) // TODO : voir si l'on doit ajouter Rating ici
        {
            if (id != appartement.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(appartement);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppartementExists(appartement.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(appartement);
        }


        // GET: Appartements/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appartement = await _context.Appartements
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appartement == null)
            {
                return NotFound();
            }

            return View(appartement);
        }

        // POST: Appartements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var appartement = await _context.Appartements.FindAsync(id);
            _context.Appartements.Remove(appartement);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AppartementExists(int id)
        {
            return _context.Appartements.Any(e => e.Id == id);
        }

        [HttpGet]
        public async Task<JsonResult> AddRemove(int appartId, int val)
        {
            // DEBUG :
            //Console.WriteLine("-----------------------" + _context.Appartements + "-----------------------");
            Console.Error.WriteLine("-----------------------" + _context.Appartements + "-----------------------");


            int retval = -1;
            var userId = await GetCurrentUserId();

            if (val == 1)
            {
                // if a record exists in UserMovies that contains both the user’s
                // and movie’s Ids, then the movie is in the watchlist and can
                // be removed
                var appart = _context.UserAppartements.FirstOrDefault(x => x.AppartementId == appartId && x.UserId == userId);
                if (appart != null)
                {
                    _context.UserAppartements.Remove(appart);
                    retval = 0;
                }
                else
                {
                    retval = 2;
                }
            }
            else
            {
                // the movie is not currently in the watchlist, so we need to
                // build a new UserMovie object and add it to the database
                //int rating = 0;// QUESTION : pourquoi je ne peux pas accèder à la liste d'appartement ? (comme la ligne en dessous) // mmm en fait si ça marche je comprends pas pk...
                int rating = _context.Appartements.Find(appartId).Rating;

                _context.UserAppartements.Add(
                    new UserAppartement
                    {
                        UserId = userId,
                        AppartementId = appartId,
                        Visited = false,
                        Rating = rating,
                        Rated = false
                    }
                );

                retval = 1;
            }
            // now we can save the changes to the database
            await _context.SaveChangesAsync();
            // and our return value (-1, 0, or 1) back to the script that called
            // this method from the Index page
            return Json(retval);
        }

        [HttpGet]
        public async Task<JsonResult> Rate(int appartId, int val)
        {
            int retval = -1;
            var userId = await GetCurrentUserId();
            var user = await GetCurrentUserAsync();
            bool alreadyRated = _context.UserAppartements.FirstOrDefault(x => x.AppartementId == appartId && x.UserId == userId).Rated;

            if (val == 1)
            {
                var appart = _context.Appartements.FirstOrDefault(x => x.Id == appartId);

                if (appart != null)
                {
                    if (!alreadyRated)
                    {
                        //RatingInfo info = new RatingInfo { UserId = userId, AppartementId = appartId };
                        //user.RatingInfo.Add(info);

                        _context.RatingInfos.Add(

Razor_Pre_TPI_AppartRental/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Razor_Pre_TPI_AppartRental</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 @{ if (User.IsInRole("Admin")) { Write("bg-danger"); } else {Write("bg-white"); } }">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Razor_Pre_TPI_AppartRental</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Wishlist" asp-action="Index">My Wishlist</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Appartements" asp-action="Index">Appartements</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Razor_Pre_TPI_AppartRental - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>